### ISSUE TITLE
toolz 0.8.2 and python 3.7 not compatible

### ISSUE THREAD

**Issue by hirenmayani** [TheGadflyProject/TheGadflyProject#69]
I tried installing requirements using - 
 pip install -r requirements.txt
and I received the following error - 
Collecting toolz==0.8.2 (from -r requirements.txt (line 40))
  Using cached https://files.pythonhosted.org/packages/75/9c/a26de5efd56009e15af607bff6d2a395631e3c20e7c64b861c9bc4b34288/toolz-0.8.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/3b/vcp2s8r53nqbt7xv_cn9b1rw0000gn/T/pip-install-u2cfof2b/toolz/setup.py", line 5, in <module>
        import toolz
      File "/private/var/folders/3b/vcp2s8r53nqbt7xv_cn9b1rw0000gn/T/pip-install-u2cfof2b/toolz/toolz/__init__.py", line 3, in <module>
        from .functoolz import *
      File "/private/var/folders/3b/vcp2s8r53nqbt7xv_cn9b1rw0000gn/T/pip-install-u2cfof2b/toolz/toolz/functoolz.py", line 501
        f.__name__ for f in reversed((self.first,) + self.funcs),
        ^
    SyntaxError: Generator expression must be parenthesized
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/3b/vcp2s8r53nqbt7xv_cn9b1rw0000gn/T/pip-install-u2cfof2b/toolz/

**Comment by pastet89** [comment]
I have the same issue.
